apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-newTestService
  description: virtual service to test plugins with github
  annotations: {}
spec:
  type: service
  lifecycle: production
  owner: architecture
